# Generated by Django 5.2.4 on 2025-08-22 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_followers_alter_user_following"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="verefied",
            new_name="verified",
        ),
        migrations.AlterField(
            model_name="user",
            name="bio",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
