# Generated by Django 5.2.4 on 2025-08-22 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_rename_verefied_user_verified_alter_user_bio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="cover",
            field=models.ImageField(
                default="defaults/cover.avif", upload_to="cover_images/"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="profile",
            field=models.ImageField(
                default="defaults/profile.png", upload_to="profile_images/"
            ),
        ),
    ]
