# Generated by Django 5.2.5 on 2025-08-22 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_cover_alter_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cover',
            field=models.ImageField(default='defaults/cover.png', upload_to='cover_images/'),
        ),
    ]
