# Generated by Django 5.2.4 on 2025-09-05 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_user_cover"),
        ("users", "0005_remove_user_followers_remove_user_following_and_more"),
    ]

    operations = []
